name: week7_institute_project_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  archive: ^3.4.10
  cloud_firestore: ^5.1.0
  connectivity_plus: ^6.0.4
  cupertino_icons: ^1.0.6
  excel: ^4.0.2
  external_path: ^1.0.3
  file_picker: ^8.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^8.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.0.11
  pdf: ^3.3.0
  printing: ^5.6.0
  syncfusion_flutter_charts: ^20.2.44
  url_launcher: ^6.0.15

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

  assets:
    - assets/NTEM.png
    - assets/iat_logo.jpg
    - assets/iat_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
