// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPDmiK581LEPBGCX4ssmLT6lSt4Qa9Lqk',
    appId: '1:607784019051:web:5fea754fc55db9699cfd2e',
    messagingSenderId: '607784019051',
    projectId: 'institute-money-management-2',
    authDomain: 'institute-money-management-2.firebaseapp.com',
    storageBucket: 'institute-money-management-2.appspot.com',
    measurementId: 'G-ECQ877V7DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnn5FqV26eF12TkioGN2n00Zsogt9dZG0',
    appId: '1:607784019051:android:24ee42cad67a8bfc9cfd2e',
    messagingSenderId: '607784019051',
    projectId: 'institute-money-management-2',
    storageBucket: 'institute-money-management-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6izQk1r1gEPc4yE3dX3-WDIcsbpN_WYo',
    appId: '1:607784019051:ios:f4e0b45c6985b3719cfd2e',
    messagingSenderId: '607784019051',
    projectId: 'institute-money-management-2',
    storageBucket: 'institute-money-management-2.appspot.com',
    iosBundleId: 'com.example.week7InstituteProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6izQk1r1gEPc4yE3dX3-WDIcsbpN_WYo',
    appId: '1:607784019051:ios:f4e0b45c6985b3719cfd2e',
    messagingSenderId: '607784019051',
    projectId: 'institute-money-management-2',
    storageBucket: 'institute-money-management-2.appspot.com',
    iosBundleId: 'com.example.week7InstituteProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPDmiK581LEPBGCX4ssmLT6lSt4Qa9Lqk',
    appId: '1:607784019051:web:aa2f6d9bda4cdeb59cfd2e',
    messagingSenderId: '607784019051',
    projectId: 'institute-money-management-2',
    authDomain: 'institute-money-management-2.firebaseapp.com',
    storageBucket: 'institute-money-management-2.appspot.com',
    measurementId: 'G-GMGDWKGQQS',
  );
}
